### ISSUE TITLE
drf method to change order doesn't update the order

### ISSUE THREAD

**Issue by elhassane47** [django-ordered-model/django-ordered-model#215] opened 2020-04-21 22:45 UTC
I use django ordered model to order my lines. when i drag and drop the file order from the front end.

I call and endpoint to move the file to the next position. but in the response the order doesn't change.

here is code

`models.py`

```
class Line(OrderedModel):  
    """
    Represents a segmented line from a document
    """
    # box = gis_models.PolygonField()  # in case we use PostGIS

    content = models.CharField(max_length=200,null=True,blank=True)
    document = models.ForeignKey(Document,
                                      on_delete=models.CASCADE,
                                      related_name='lines')
    # text direction
    order_with_respect_to = 'document'
    version_ignore_fields = ('document', 'order')

    external_id = models.CharField(max_length=128, blank=True, null=True)

    class Meta(OrderedModel.Meta):
        pass
```

`serialiezers.py`

```
class LineMoveSerializer(serializers.ModelSerializer):
    index = serializers.IntegerField()

    class Meta:
        model = Line
        fields = ('index',)

    def __init__(self, *args, line=None, **kwargs):
        self.line = line
        super().__init__(*args, **kwargs)

    def move(self):
        self.line.to(self.validated_data['index'])
```

`views.py`

```
@action(detail=True, methods=['post'])
def move(self, request, document_pk=None, pk=None):

    line = get_object_or_404(Line, pk=pk)
    serializer = LineMoveSerializer(line=line, data=request.data)
    if serializer.is_valid():
        serializer.move()
        lines = Line.objects.filter(document_part=part_pk).values('pk','order')
        return Response(status=status.HTTP_200_OK,data= {'moved': lines})
    else:
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
```

**Comment by imomaliev** [comment] 2020-05-11 14:27
Does it give any errors?

**Comment by shuckc** [comment] 2022-02-19 23:27
I dug into a related issue for #264 - the cause in that case was that our order field is marked as read-only, which causes DRF to prevent changes. I can see you have defined your own `IntegerField` to address this. 
I will close this issue as I believe the `Serializer` on that PR will solve the problem for you.

**Closed by shuckc** 2022-02-19 23:27 UTC
